targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          class_name_pattern:
            'Service$|Manager$|ViewModel$'
      json_serializable:
        options:
          explicit_to_json: true
      reflectable:
        generate_for:
          - lib/main.dart
        options:
          formatted: true
