targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          class_name_pattern:
            'Service$|Manager$'
      json_serializable:
        options:
          explicit_to_json: true
