name: fast_dotnet_ef
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  process_run: ^0.12.2+2
  injectable: ^1.5.0
  get_it: ^7.2.0
  collection: ^1.15.0
  tabbed_view: ^1.10.0
  cupertino_icons: ^1.0.2
  file_picker: ^4.2.7
  logging: ^1.0.2
  sqflite: ^2.0.1
  sqflite_common_ffi: ^2.1.0
  sqflite_migration: ^0.3.0
  path_provider: ^2.0.8
  json_annotation: ^4.4.0
  quiver: ^3.0.1+1
  synchronized: ^3.0.0
  reflectable: ^3.0.4
  intl: ^0.17.0
  shared_preferences: ^2.0.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  injectable_generator: ^1.5.2
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/
