name: ef_steroid
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  injectable: ^1.5.3
  get_it: ^7.2.0
  collection: ^1.15.0
  tabbed_view: ^1.10.0+1
  cupertino_icons: ^1.0.4
  file_picker: ^4.4.0
  logging: ^1.0.2
  sqflite: ^2.0.2
  sqflite_common_ffi: ^2.1.0+2
  sqflite_migration: ^0.3.0
  path_provider: ^2.0.9
  json_annotation: ^4.4.0
  quiver: ^3.0.1+1
  synchronized: ^3.0.0
  reflectable: ^3.0.6
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  darq: ^1.1.1
  async_task: ^1.0.17
  bot_toast: ^4.0.1
  desktop_window: ^0.4.0
  uuid: ^3.0.6
  equatable: ^2.0.3
  xml: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  injectable_generator: ^1.5.3
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/
