// <auto-generated />

using EfSteroidSqlite.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfSteroidSqlite.Migrations
{
    [DbContext(typeof(EfSteroidDbContext))]
    [Migration("20220116115553_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("EfSteroidSqlite.Entity.EfPanel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigFileUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectEfType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EfPanels");
                });
#pragma warning restore 612, 618
        }
    }
}
