name: Flutter CD
env:
  GITHUB_RELEASE_ARTIFACTS_DIR: artifacts
  MACOS_GITHUB_ARTIFACT_NAME_SHARED: macos-artifacts
  MACOS_APPCAST_GITHUB_ARTIFACT_NAME_SHARED: macos-appcast
on:
  push:
    branches:
      - production

jobs:
  Flutter-CI:
    uses: ./.github/workflows/flutter-ci.yml
    secrets:
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
      APP_STORE_CONNECT_PRIVATE_KEY_ID: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY_ID }}
      P12_SIGNING_CERTIFICATE: ${{ secrets.P12_SIGNING_CERTIFICATE }}
      P12_SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.P12_SIGNING_CERTIFICATE_PASSWORD }}
      P12_SIGNING_CERTIFICATE_KEYCHAIN_PASSWORD: ${{ secrets.P12_SIGNING_CERTIFICATE_KEYCHAIN_PASSWORD }}
      SPARKLE_PRIVATE_KEY: ${{ secrets.SPARKLE_PRIVATE_KEY }}

  macOS-CD:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - Flutter-CI
    steps:
      - name: Download macOS Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: ${{ env.MACOS_GITHUB_ARTIFACT_NAME_SHARED }}
          path: ${{ env.GITHUB_RELEASE_ARTIFACTS_DIR }}
      - uses: ncipollo/release-action@v1
        name: Publish macOS Artifact
        with:
          artifacts: "artifacts/**/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.Flutter-CI.outputs.version }}

  github-pg-CD:
    runs-on: ubuntu-latest
    needs:
      - macOS-CD
    steps:
      - name: Download macOS appcast.xml
        uses: actions/download-artifact@v3.0.0
        with:
          name: ${{ env.MACOS_APPCAST_GITHUB_ARTIFACT_NAME_SHARED }}
          path: ${{ env.GITHUB_RELEASE_ARTIFACTS_DIR }}
      - name: Deploy macOS appcast
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.GITHUB_RELEASE_ARTIFACTS_DIR }}
