name: Flutter CICD
on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]
  workflow_dispatch:
env:
  FLUTTER_WINDOWS_VERSION: stable
  FLUTTER_MACOS_VERSION: master
  DATABASE_USERNAME: SA
  DATABASE_SA_PASSWORD: fdkngx4tak7vka8JNT

jobs:
  Windows-CI:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: $FLUTTER_WINDOWS_VERSION

      - name: Check Dart code style
        run: flutter format lib --set-exit-if-changed

      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Install dotnet-ef
        run: dotnet tool install -g dotnet-ef

      - name: Build CsprojTool artifacts
        shell: pwsh
        working-directory: tools/CsprojTool
        run: ./BuildArtifacts.ps1

      - name: Install packages
        run: flutter pub get
      - name: Run build_runner
        run: flutter pub run build_runner build

      - name: Install SQL Server
        uses: Particular/install-sql-server-action@main
        with:
          connection-string-env-var: SQL_SERVER_CONNECTION_STRING
      - name: Create database user
        run: sqlcmd -S localhost -U SA -P $env:DATABASE_SA_PASSWORD
        shell: pwsh

      - name: Run test
        run: flutter test --coverage

      - name: Build Windows artifacts
        run: flutter build windows

  macOS-CI:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: $FLUTTER_MACOS_VERSION

      - name: Check Dart code style
        run: flutter format lib --set-exit-if-changed

      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Install dotnet-ef
        run: dotnet tool install -g dotnet-ef

      - name: Install needle
        run: brew install needle

      - name: Install packages
        run: flutter pub get
      - name: Run build_runner
        run: flutter pub run build_runner build

      # Enable macOS desktop support. Remove this when Flutter marks macOS support as stable.
      - name: Enable macOS Desktop
        run: flutter config --enable-macos-desktop

      - name: setup-docker
        uses: docker-practice/actions-setup-docker@1.0.8

      - name: Run docker to install MSSQL
        run: ./Scripts/docker-setup.ps1 $env:DATABASE_SA_PASSWORD
        shell: pwsh

      # Comment out this until I figure out how to set up SQL in docker for testing purpose.
      - name: Run test
        run: flutter test --coverage

      - name: Build macOS artifacts
        run: flutter build macos


