name: Flutter CD
env:
  GITHUB_RELEASE_ARTIFACTS_DIR: artifacts
on:
  push:
    branches:
      - production

jobs:
  Flutter-CI:
    uses: ./.github/workflows/flutter-ci.yml

  macOS-CD:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - Flutter-CI
    steps:
      - name: Download macOS Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: ${{ needs.Flutter-CI.outputs.macos_github_artifact_name }}
          path: ${{ env.GITHUB_RELEASE_ARTIFACTS_DIR }}
      - uses: ncipollo/release-action@v1
        name: Publish macOS Artifact
        with:
          artifacts: "artifacts/**/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.Flutter-CI.outputs.version }}

  github-pg-CD:
    runs-on: ubuntu-latest
    needs:
      - macOS-CD
    steps:
      - name: Download macOS appcast.xml
        uses: actions/download-artifact@v3.0.0
        with:
          name: ${{ needs.Flutter-CI.outputs.macos_appcast_github_artifact_name }}
          path: ${{ env.GITHUB_RELEASE_ARTIFACTS_DIR }}
      - name: Deploy macOS appcast
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.GITHUB_RELEASE_ARTIFACTS_DIR }}
